version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - service-status
      - forms
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - matomo_data:/var/www/html:rw
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=etna
      - POSTGRES_DB=etna
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  # catalogue:
  #   container_name: catalogue
  #   image: ghcr.io/nationalarchives/ds-catalogue:25.11.12.1568
  #   env_file:
  #     - .env
  #   environment:
  #     - RUNTIME=production
  #     - ENVIRONMENT_NAME=develop
  #     - SENTRY_DSN=https://3e24f4f474026e113e6dcdeccf2abded@o1230303.ingest.us.sentry.io/4507458864087040
  #     - DJANGO_SETTINGS_MODULE=config.settings.staging
  #     - ALLOWED_HOSTS=develop.tna.dblclk.dev,tna.dblclk.dev,*
  #     - SECRET_KEY=${SECRET_KEY}
  #     # - DATABASE_HOST=postgres
  #     # - DATABASE_PORT=5432
  #     # - DATABASE_NAME=etna
  #     # - DATABASE_USER=etna
  #     # - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
  #     # - DATABASE_ENGINE=django.db.backends.postgresql
  #     - COOKIE_DOMAIN=tna.dblclk.dev
  #     - CSP_STYLE_SRC='self',https://fonts.googleapis.com,https://p.typekit.net,https://use.typekit.net
  #     - CSP_SCRIPT_SRC='self',https://www.googletagmanager.com/gtm.js
  #     - CSP_FONT_SRC='self',https://fonts.gstatic.com,https://use.typekit.net
  #     - CSP_IMG_SRC='self',https://www.nationalarchives.gov.uk,https://www.googletagmanager.com
  #     - CSP_FRAME_SRC='self',https://www.youtube.com
  #     - ROSETTA_API_URL=https://rosetta-staging.k-int.com/rosetta/data
  #     - ALLOW_INSECURE=true
  #     # - DELIVERY_OPTIONS_API_URL=http://discovery-services.live.local/DiscoveryDeliveryOptionsapi/api/DeliveryOptions
  #     - DCS_PREFIXES=HO 616,AB 41,J 14,LOC 5,HO 397,ILB 2,LEV 1,GTI 2,GTI 102,ICSA 1,ICSA 2,ICSA 3,ICSA 4,ICSA 5,ICSA 6,ICSA 7,ES 38
  #     - STAFFIN_IP_ADDRESSES=172.31.8.0/22,10.96.0.0/13,10.104.0.0/13,10.95.48.0/24,172.31.0.0/21,10.252.16.0/21,10.252.21.0/24,10.114.1.0/24
  #     - ONSITE_IP_ADDRESSES=10.136.0.0/19,167.98.93.94/32,10.120.0.0/13,10.112.0.0/13
  #     - WAGTAIL_API_URL=https://wagtail.nationalarchives.gov.uk/api/v2
  #     - GA4_ID=GTM-KX8ZWVZG
  #   expose:
  #     - 8080
  service-status:
    container_name: service-status
    image: ghcr.io/nationalarchives/ds-service-status:26.09.14.149
    env_file:
      - .env
    environment:
      - APPLICATION_PROTOCOL=http
      - ENVIRONMENT_NAME=staging
      - CONFIG=config.Staging
      - SECRET_KEY=${SECRET_KEY}
      - COOKIE_DOMAIN=tna.dblclk.dev
      - CSP_STYLE_SRC='self',https://www.nationalarchives.gov.uk/enrichment/,https://fonts.googleapis.com,https://p.typekit.net,https://use.typekit.net
      - CSP_FONT_SRC='self',https://fonts.gstatic.com,https://use.typekit.net
      - CSP_IMG_SRC='self',https://www.nationalarchives.gov.uk/enrichment/
      - CSP_SCRIPT_SRC='self',https://www.nationalarchives.gov.uk/enrichment/
      - CSP_CONNECT_SRC='self',https://www.nationalarchives.gov.uk/enrichment/
      - UPTIME_KUMA_URL=https://uptime.tna.dblclk.dev
      - UPTIME_KUMA_STATUS_PAGE_SLUG=nationalarchives
      - UPTIME_KUMA_JWT=${UPTIME_KUMA_JWT}
      - ALLOW_INSECURE=true
      - CACHE_DEFAULT_TIMEOUT=300
      - _SENTRY_DSN=https://f0dfd41f5e17da117bde6cde2371045f@o1230303.ingest.us.sentry.io/4509966773387264
    expose:
      - 8080
  forms:
    container_name: forms
    image: ghcr.io/nationalarchives/ds-forms:26.03.25.100
    env_file:
      - .env
    environment:
      - APPLICATION_PROTOCOL=http
      - ENVIRONMENT_NAME=staging
      - CONFIG=config.Staging
      - SECRET_KEY=${SECRET_KEY}
      - COOKIE_DOMAIN=tna.dblclk.dev
      - CSP_STYLE_SRC='self',https://fonts.googleapis.com,https://p.typekit.net,https://use.typekit.net
      - CSP_FONT_SRC='self',https://fonts.gstatic.com,https://use.typekit.net
      - ALLOW_INSECURE=true
      - SESSION_REDIS_URL=redis://redis:6379/0
      - RATELIMIT_REDIS_URL=redis://redis:6379/1
      - RATELIMIT_DEFAULT=4 per 2 seconds
      - ALTCHA_HMAC_KEY=${SECRET_KEY}
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/2
    expose:
      - 8080
  redis:
    container_name: redis
    image: redis:latest
    # command: /bin/sh -c "redis-server --user redis --requirepass ${REDIS_PASSWORD}"
    # env_file:
    #   - .env
    # environment:
    #   - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptime_kuma2:/app/data
      - ./uptime_kuma_data:/app_data
      - ../uptime_kuma_backups:/backup
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  matomo:
    container_name: matomo
    image: matomo:fpm-alpine
    env_file:
      - .env
    environment:
      - MATOMO_DATABASE_HOST=mysql
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=${MYSQL_MATOMO_PASSWORD}
      - MATOMO_DATABASE_DBNAME=matomo
    restart: unless-stopped
    volumes:
      - matomo_data:/var/www/html:rw
  mysql:
    container_name: mysql
    image: mysql:lts
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=${MYSQL_MATOMO_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql:rw
volumes:
  pgdata:
  media:
  redis_data:
  uptime_kuma:
  uptime_kuma2:
  portainer_data:
  matomo_data:
  mysql_data:
